development:
  adapter: postgresql
  encoding: unicode
  database: ofn_dev
  pool: 5
  host: localhost
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ofn_test
  pool: 5
  host: localhost
  username: postgres
  password:

#not used with heroku
production:
  adapter: postgresql
  encoding: unicode
  database: ofn_prod
  pool: 5
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: ofn_prod
  pool: 5
  username: postgres
  password:
